#!/bin/sh
set -e
echo "bootstraping environment..."
set -x

# this script is designed to be placed in a "bin/" sub dir of a buildout project
BUILDOUT_DIR=`dirname "$0"`/..
cd $BUILDOUT_DIR

# Only overwrite the local.cfg if it is not presently there
if [ ! -f buildout/local.cfg ]
then
    if [ -f buildout/local.cfg.in ]
    then
        cp buildout/local.cfg.in buildout/local.cfg
    else
        touch buildout/local.cfg
    fi
fi

# Create virtual environment upgrade pip and install setuptools and zc.buildout
python3 -m venv buildout/py
buildout/py/bin/pip install -U pip
buildout/py/bin/pip install -U setuptools
buildout/py/bin/easy_install -U zc.buildout

# Pull sources first before first buildout
buildout/py/bin/buildout -N install mr.developer
bin/develop update
